version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:3000  # Environment variable for the backend URL

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/ecommerce  # MongoDB connection string
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"  # Host port 27018 maps to container port 27017
    volumes:
      - mongo-data:/data/db  # Persistent data volume for MongoDB

volumes:
  mongo-data:  # Define the persistent data volume