# Use Node.js 16.20.2 runtime as a parent image
FROM node:22.12.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the backend port
EXPOSE 3000

# Command to run the application
CMD ["node", "server.js"]